# Generated by Django 4.2 on 2023-04-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Vehicle Name")),
                (
                    "reg_no",
                    models.CharField(
                        max_length=20, verbose_name="Vehicle Registration Number"
                    ),
                ),
                (
                    "on_trip",
                    models.BooleanField(
                        default=False, verbose_name="Vehicle is on trip"
                    ),
                ),
                ("seats", models.IntegerField(verbose_name="Vehicle Seat Limit")),
                (
                    "color_name",
                    models.CharField(max_length=50, verbose_name="Vehicle Color Name"),
                ),
                (
                    "color_code",
                    models.CharField(max_length=6, verbose_name="Vehicle Color Code"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Vehicle Model Name"),
                ),
                (
                    "model_manufacturer",
                    models.CharField(
                        max_length=100, verbose_name="Vehicle Model Manufacturer"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Vehicle is active"),
                ),
                ("slug", models.TextField(unique=True, verbose_name="Vehicle Slug")),
            ],
            options={
                "verbose_name_plural": "Vehicles",
                "ordering": ["-modification_date", "-creation_date", "name"],
            },
        ),
    ]
