# Generated by Django 4.2 on 2023-04-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0003_remove_vehicledetails_vehicle_daily_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledetails",
            name="vehicle_main",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle",
                to="vehicles.vehicle",
            ),
        ),
    ]
